version: "3.9"
services:
    linux:
        build: .
        image: "asone:latest"
        volumes:
            - ${PWD}:/workspace
            - $HOME/.Xauthority:/root/.Xauthority:rw
        network_mode: "host"
        restart: always
        environment:
            DISPLAY: $DISPLAY
    linux-gpu:
        build: .
        image: "asone:latest"
        volumes:
            - ${PWD}:/workspace
            - $HOME/.Xauthority:/root/.Xauthority:rw
        network_mode: "host"
        environment:
            DISPLAY: $DISPLAY
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

